### ISSUE TITLE
Add the citation information as a .bib file

### ISSUE THREAD

**Issue by AndyClifton** [SWE-UniStuttgart/ViConDAR#1]
**Is your feature request related to a problem? Please describe.**
You provide a citation which is formatted using a non-standard style. I want a citation that can be formatted according to the requirements of the journal I use.

**Describe the solution you'd like**
Make it easier for me to include the citation in my papers by including it as a .bib file.

**Describe alternatives you've considered**
N/A

**Additional context**
This may work:

```@article{pettas_garcía_kretschmer_rinker_clifton_cheng_2020,
title={A numerical framework for constraining synthetic wind fields with lidar measurements for improved load simulations},
DOI={10.2514/6.2020-0993},
journal={AIAA Scitech 2020 Forum},
author={Pettas, Vasilis and García, Francisco Costa and Kretschmer, Matthias and Rinker, Jennifer M. and Clifton, Andrew and Cheng, Po Wen},
year={2020},
month={May}}

**Comment by Vaspe** [comment]
Added the .bib format of the citation in the readme.
