### ISSUE TITLE
Provide a release version

### ISSUE THREAD

**Issue by AndyClifton** [SWE-UniStuttgart/ViConDAR#2]
**Is your feature request related to a problem? Please describe.**
At the moment I am able to download the code from Github as a repository, but there is no clearly-defined release e.g. the version of the code that was used to create the plots shown at AIAA Scitech 2020.

**Describe the solution you'd like**
Please create a release at https://github.com/SWE-UniStuttgart/ViConDAR/releases

**Describe alternatives you've considered**
Downloading the source from the repo. However, this does not give me a stable version of the code (e.g. v0.1 corresponds to the Scitech 2020 plots)

**Additional context**
N/A

**Comment by Vaspe** [comment]
I think we should wait a bit more for the initial release version as there are still things that need to be refined in terms of code clarity/commenting as well as some modules that are only functional in specific cases for now.

**Comment by AndyClifton** [comment]
In the interests of repeatability, I think it would still be worth creating a version 0.1 that reflects the code used for the publication.

**Comment by Vaspe** [comment]
Release v1.0 done
