### ISSUE TITLE
Provide a DOI for the code itself

### ISSUE THREAD

**Issue by AndyClifton** [SWE-UniStuttgart/ViConDAR#3]
**Is your feature request related to a problem? Please describe.**
The only way to reference the code is via the Scitech 2020 paper. The code has no DOI.

**Describe the solution you'd like**
Please consider also checking this release version in to Xenodo or other repository so that it can get a DOI. This would allow me to reference the code directly.

**Describe alternatives you've considered**
Referencing the Scitech 2020 paper. This is not satisfactory as it is still not clear what code was being used and any results are not reproducible.

**Additional context**
N/A

**Comment by Vaspe** [comment]
I think the SciTech paper is a good reference as it describes the functionality of the code. All the results shown there are used using ViConDAR and the settings used as well as the generation of the turbsim baseline wind fields are thoroughly documented in he paper
