### ISSUE TITLE
Changes on version2.0

### ISSUE THREAD

**Issue by PacoCosta** [SWE-UniStuttgart/ViConDAR#7]
This changes are made on the current ViConDAR version2.0
- get_LidarOutput: 
  - Line 364: lenght--> size
  - Line 404: Commented out  decompose to components section

**Comment by Vaspe** [comment]
It seems that the new functionality breaks when decomposing the vector which indicates that the format of the variable has been changed. We need to fix this

**Comment by PacoCosta** [comment]
Bug found: 

-  we where using ```length``` in a loop. The problem with ```length``` is that it outputs the longest dimension in a matrix, so if at some point we have more points to average than slices it takes the wrong dimension
