### ISSUE TITLE
NEW implementations

### ISSUE THREAD

**Issue by PacoCosta** [SWE-UniStuttgart/ViConDAR#9]
- ```V_spec```: peak detection method
- ```Weighting _probe```: Weighting function for pulsed and CW lidars
- ```InputParameters.m```: 
   - Flags: 
     - Qlundar
     - get_TI_Vs_RZ
     - Probe weighting function: ""pulsed", "cw" or "mean"
     - Peak detection method: "maximum", "median" or "centroid"
   - truncation val
   - Create random patterns: should go in a function
- ```getLidarOutput.m```
   - NEW: line ~272   
- ```ViConDAR.m```: 
   - flag_Qlundar line 229
- Scripts: 
  - ```getTI_Vs_Rz.m```
  - ```Qlundar_wrapper.m```
  - ```ceilS.m``` and ```floorS.m``` (```V_spec```)

**Comment by Vaspe** [comment]
It seems there are a bit more input parameters changed. Please document all the new changes
